---
title: "leslie-practice"
format: html
editor: visual
---

## #Matrices

```{r}
#make a sequence of values from 1 to 10
my_values <-seq (from=1, to = 10, by =1)

#look at values(always!)
my_values
```

```{r}
#convert to matrix
my_matrix <- matrix(data = my_values,
                    nrow = 2,
                    ncol = 5, byrow = TRUE)
my_matrix
```

```{r}
matrix(data = my_values,
       nrow = 2,
       ncol = 3, byrow = TRUE)

```

```{r}
matrix(data = my_values,
       nrow = 3,
       ncol = 4, byrow = TRUE)

```

## matrix math

```{r}
4 * my_matrix

```

```{r}
my_values2 <- seq(from = 21, to = 30)
my_matrix2 <- matrix(my_values2,nrow = 2, byrow = TRUE)
my_matrix2

```

```{r}
my_matrix - my_matrix2
```

## matrix multiplication

```{r}
#make a couple of 2 * 2 matrices
cats <- matrix(data = c(0, 4, 3, 1), nrow = 2, byrow = TRUE)
dogs <- matrix(data = c(6, -3, 0, 2), nrow = 2, byrow = TRUE)

cats
dogs

```

```{r}
cats %*% dogs #dot product

```

## leslie matrix example

```{r}
#create a projection matrix
insect_leslie <- matrix(c(0, 0, 600, 0.2, 0, 0, 0, 0, 0.8, 0),
                        nrow =3, ncol =3,
                        byrow = TRUE)
insect_leslie
```

```{r}
#Specify initial conditions
#insect lifestage population size (year 0)
insect_y0 <- c(12000, 700, 500)

```

```{r}
#find the population for each lifestage at year 1
insect_y1 = insect_leslie %*% insect_y0
insect_y1


```

```{r}
#find the population for each lifestage at year 2
insect_y2 = insect_leslie %*% insect_y1
insect_y3 = insect_leslie %*% insect_y2
insect_y4 = insect_leslie %*% insect_y3
insect_y4

```

## another leslie matrix example

```{r}
#make the projection matrix
tree_leslie <- matrix(c(0, 0, 5000, 0.10, 0, 0, 0, 0.06, 0.95),
                      nrow = 3,
                      ncol = 3, byrow = TRUE)
tree_leslie

```

```{r}
#create the initial condition
tree_0 <- c(5000, 0, 0)

#year 1
tree_1 <- tree_leslie %*% tree_0
tree_1

#year 2
tree_2 <- tree_leslie %*% tree_1
tree_2

#year 3
tree_3 <- tree_leslie %*% tree_1
tree_3

#year 4
tree_4 <- tree_leslie %*% tree_3
tree_4

```
